```yaml
name: docker-build-and-test

on:
  push:
    branches:
      - develop

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push my-app:latest

  run-integration-tests:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Pull Docker Image
        run: docker pull my-app:latest

      - name: Run Integration Tests
        run: docker run my-app:latest pytest
      - name: Store Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results/

  deploy-staging:
    runs-on: [self-hosted, linux]
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy to Staging
        run: ./deploy.sh
```