
name: ci.yml

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        python-version: [3.7]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run code linting
        run: eslint .
      - name: Run unit tests
        run: npm test
      - name: Fail if errors or failures occur
        if: ${{ failure() }}
        run: exit 1

  coverage-report:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install nyc
      - name: Run coverage tool
        run: nyc report
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/