
name: branch-protection

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check for code changes
        uses: actions/github-script@v3
        with:
          script: |
            const commits = await github.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha
            });
            const changedFiles = await github.repos.listFilesForCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha
            });
            if (commits.data.length > 0 && changedFiles.data.length > 0) {
              core.setOutput("changes", true);
            } else {
              core.setOutput("changes", false);
            }
      - name: Get code coverage report
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
          path: code-coverage-report
      - name: Verify code linting and unit tests
        uses: actions/download-artifact@v2
        with:
          name: code-linting-and-unit-tests
          path: