
# This is a multi-stage deployment YAML file

name: multi-stage-deploy

on:
  push:
    branches: 
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build application bundle
        run: npm run build
    env:
      NODE_ENV: production

  stage:
    runs-on: staging
    needs: build
    environment:
      name: staging
    steps:
      - name: Deploy to staging
        uses: some-deploy-action@v1
        with:
          app: ${{ needs.build.outputs.app }}
          env: staging
    env:
      API_URL: staging-api-url
      DB_CONNECTION: staging-db-connection

  production-deploy:
    runs-on: production
    needs: build
    environment:
      name: production
    steps:
      - name: Deploy to production
        uses: some-deploy-action@v1
        with:
          app: ${{ needs.build.outputs.app }}
          env: production
        env:
          API_URL: ${{