
name: multi-stage-deploy
on:
  push:
    branches: [production]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build
  stage:
    runs-on: staging
    needs: build
    steps:
      - name: Deploy application
        uses: actions/github-script@v3
        with:
          script: node deploy.js
      - name: Configure environment variables
        run: |
          echo "API_URL: ${{ secrets.API_URL }}" >> $GITHUB_ENV
          echo "DB_CONNECTION: ${{ secrets.DB_CONNECTION }}" >> $GITHUB_ENV
  production-deploy:
    runs-on: production
    needs: build
    steps:
      - name: Deploy application
        uses: actions/github-script@v3
        with:
         
