
name: multi-stage-deploy.yml
on:
  push:
    branches:
      - production
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build
  stage:
    runs-on: staging
    needs: build
    steps:
      - name: Deploy application
        run: npm run deploy
      - name: Configure staging environment
        run: set-env API_URL=example.com DB_CONNECTION=staging
  production-deploy:
    runs-on: production
    needs: build
    steps:
      - name: Deploy application
        run: npm run deploy
      - name: Access sensitive environment variables
        run: access-secrets-manager