
name: multi-stage-deploy.yml

on:
  push:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build application bundle
        run: npm run build
  stage:
    runs-on: [staging environment runner]
    needs: [build]
    steps:
      - name: Deploy application
        run: <insert deploy command here>
      - name: Configure environment
        run: <insert environment configuration command here>
  production-deploy:
    runs-on: [production environment runner]
    needs: [build]
    steps:
      - name: Deploy application
        run: <insert deploy command here>
      - name: Access sensitive environment variables
        uses: <insert secrets manager here>