
name: api-docs.yml

on:
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install npm
        run: npm install
      - name: Install Swagger or JSDoc
        run: npm install swagger or jsdoc
      - name: Generate API documentation
        run: npm run generate-docs
      - name: Archive documentation
        uses: actions/upload-artifact@v2
        with:
          name: generated-docs
          path: <generated-docs-folder>
  
  deploy-docs:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: generated-docs
          path: <generated-docs-folder>
      - name: Deploy documentation
        run