
name: docker-build-and-test.yml

on:
  push:
    branches: [develop]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: my-app:latest
          registry: docker.io
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  run-integration-tests:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Pull Docker image
        uses: docker://my-app:latest
      - name: Run integration tests
        run: docker run my-app:latest pytest
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results
  deploy-staging:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-l