
multi-stage-deploy.yml:

name: multi-stage-deploy

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build
    
  stage:
    runs-on: staging
    needs: build
    environment:
      name: staging
    steps:
      - name: Deploy application
        run: npm run deploy
      - name: Configure environment variables
        run: npm run configure-env
    
  production-deploy:
    runs-on: production
    needs: build
    environment:
      name: production
    steps:
      - name: Deploy application
        run: npm run deploy
      - name: Configure environment variables
        run: npm run configure-env
      - name: Access sensitive environment variables
        run: npm