---
name: e2e-tests
on:
  pull_request:
    branches:
      - test
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        db-tool: [mysql, postgresql]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Database Tool
        run: sudo apt-get install ${{ matrix.db-tool }}
      - name: Connect to Test Database
        run: ${{ matrix.db-tool }} -u username -p password -D test_database < sample_data.sql
      - name: Start Application
        run: npm start
      - name: Run End-to-End Tests
        uses: cypress-io/github-action@v2
        with:
          record: true
      - name: Clean Up Test Database
        run: ${{ matrix.db-tool }} -u username -p password -D test_database < clean_up.sql
      - name: Fail Workflow on Test Failures
        if