
name: deploy-multi-env.yml

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install boto3

      - name: Deploy to staging
        if: ${{ github.event.branch == 'staging' }}
        needs: deploy
        steps:
          - name: Use AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_STAGING_KEY }}
              aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET }}

          - name: Configure environment variables
            run: |
              export STAGING_ENV=staging
              python configure_env.py

      - name: Deploy to production
        if: ${{ github.event.branch == 'master' }}
        needs: deploy
        steps:
          - name: Use AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS