
name: multi-stage-deploy.yml

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        run: sudo apt install nodejs
      - name: Install build tool
        run: npm install -g webpack
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: webpack

  stage:
    runs-on: staging
    needs: build
    steps:
      - name: Deploy application
        run: <insert deploy command here>
      - name: Configure staging environment
        run: <insert environment configuration command here>

  production-deploy:
    runs-on: production
    needs: build
    steps:
      - name: Deploy application
        run: <insert deploy command here>
      - name: Configure production environment
        run: <insert environment configuration command here>
      - name: Access sensitive environment variables
        run: <insert secrets manager command here>